---
- name: HDP 2.5 ambari server preinstall steps
  hosts: ambari-server
  become: yes
  vars_files:
    - vars.yml
  roles:
    - common
    - ambari-server

- name: HDP 2.5 ambari agent preinstall steps
  hosts: ambari-server
  become: yes
  vars_files:
    - vars.yml
  roles:
    - common
    - ambari-server
  
