---
- name: HDP 2.5 ambari common preinstall steps
  hosts: all
  become: yes
  vars_files:
    - vars.yml
  roles:
    - common

- name: HDP 2.5 ambari server preinstall steps
  hosts: ambari-server
  become: yes
  vars_files:
    - vars.yml
  roles:
    - ambari-server

- name: HDP 2.5 ambari agent preinstall steps
  hosts: ambari-agent
  become: yes
  vars_files:
    - vars.yml
  roles:
    - ambari-agent

