---
- name: update - update all packages
  yum:
    pkg: '*'
    state: latest
  register: common_update_check

- name: update - Reboot if packages were updated
  command: shutdown -r now 'Ansible - Reboot for update.'
  when: common_update_reboot and common_update_check | changed

- name: update - Wait for reboot
  local_action:
    module: wait_for
    host: "{{ ansible_ssh_host }}"
    port: "{{ ansible_ssh_port }}"
    delay: 30
    timeout: 600
    state: started
  become: no
  when: common_update_reboot and common_update_check | changed
